# @copyright Copyright (c) 2021 Nicolas GRELLETY
# @license https://opensource.org/licenses/GPL-3.0 GNU GPLv3
# @link https://gitlab.internal.lan/octo-project/octobaselines
# @link https://github.com/nillyr/octobaselines
# @since 1.0.0b

id: NP_ConfigMateriel_R9
title: Virtualisation de contexte d'exécution
description: |
  La fonction de virtualisation de contexte d'exécution peut être exploitée par certaines formes de rootkits pour se rendre difficilement détectables vis-à-vis du système virtualisé, anéantissant ainsi tout effort d'analyse et de rémédiation.

  La fonction de virtualisation de contexte d'exécution doit être désactivée lorsqu'elle n'est pas strictement nécessaire au fonctionnement du système.

collection_cmd: |
  cat /proc/cpuinfo | encrypt_output > NP_ConfigMateriel_R9_cpuinfo.txt

  is_package_installed sudo && SUDO_CMD="sudo"
  ${SUDO_CMD} lscpu | encrypt_output > NP_ConfigMateriel_R9_lscpu.txt
  ${SUDO_CMD} lsmod | encrypt_output > NP_ConfigMateriel_R9_lsmod.txt

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NP_ConfigMateriel_R9"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_FAIL

  if ! grep -q -E "smx|vmx" /proc/cpuinfo; then
    debug "VT-x/AMD-v is not supported by the CPU."
    STATUS=RESULT_CHECK_PASS
  fi

  is_package_installed sudo && SUDO_CMD="sudo"
  if ! ${SUDO_CMD} lsmod | grep -q -E "^kvm_(amd|intel)"; then
    debug "VT-x/AMD-v module is not loaded."
    STATUS=RESULT_CHECK_PASS
  fi

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*RESULT_CHECK_PASS
recommendation: |
  Nous recommandons la désactivation de cette fonctionnalité dans le cas où cette dernière n'est pas strictement nécessaire.
  La procédure à suivre pouvant varier d'un matériel à l'autre, il est recommandé de bien consulter la documentation associée.

level: enhanced
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/administration/guide/recommandations-de-configuration-materielle-de-postes-clients-et-serveurs-x86/
