id: NP_ConfigMateriel_R1
title: Support des instructions 64 bits par le processeur
description: |
  L'utilisation du mode 64 bits présente des avantages par rapport au mode protégé :

  - l'espace d’adressage plus important donne plus de latitude dans le choix des adresses, en particulier lorsqu'il est fait de manière aléatoire (ASLR) ;
  - la présence systématique de bits de protections NX/XD sur les pages mémoires, permettant de les déclarer non-exécutables 3 ;
  - l'adressage relatif par registre rip, plus naturel (et performant) pour du code qui peut être chargé voire exécuté indépendamment de sa position (PIC, PIE) ;
  - l'accroissement de l'espace d'adressage du noyau et des processus (de 4GiB à 128TiB) permet d'augmenter les performances de programmes nécessitant de grandes quantités de mémoire, comme certaines bases de données.

  Il est recommandé de choisir un processeur capable de supporté les instructions 64 bits.

collection_cmd: |
  lscpu | encrypt_output > NP_ConfigMateriel_R1.txt

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NP_ConfigMateriel_R1"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_FAIL

  # Option 1: use of 64-bit cpu
  uname -m | grep -q -E "x86_64|amd64|aarch64" && STATUS=RESULT_CHECK_PASS
  # Option 2: use of 32-bit cpu which supports 64-bit instructions
  lscpu | grep -q -o "64-bit" && STATUS=RESULT_CHECK_PASS

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output

verification_type: CHECK_REGEX
expected: ^\s*RESULT_CHECK_PASS
recommendation: |
  Nous recommandons d'utiliser un processeur en mesure de supporter les instructions 64 bit. Cette recommandation nécessite un changement de matériel.
level: enhanced
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/administration/guide/recommandations-de-configuration-materielle-de-postes-clients-et-serveurs-x86/
