# @copyright Copyright (c) 2021 Nicolas GRELLETY
# @license https://opensource.org/licenses/GPL-3.0 GNU GPLv3
# @link https://gitlab.internal.lan/octo-project/octobaselines
# @link https://github.com/nillyr/octobaselines
# @since 1.0.0b

id: NP_ConfigMateriel_R6
title: Activation de la fonction SMAP
description: |
  La fonctionnalité SMAP complète la fonctionnalité SMEP en ce qu'elle empêche, pour un contexte d'exécution de privilège donné, d'accéder à des pages mémoires en lecture/écriture marquées à un niveau de privilège plus faible. SMAP permet donc de détecter l'accès en lecture/écriture par le noyau à des pages mémoires situées en espace utilisateur ; elle limite ainsi les possibilités offertes à un attaquant de manipuler les données accédées par un noyau dans le but de le compromettre.

  Il est recommandé d'utiliser un processeur capable de supporter la fonctionnalité SMAP.

collection_cmd: |
  grep -m1 smep /proc/cpuinfo | encrypt_output > NP_ConfigMateriel_R6_cpu.txt

  is_package_installed sudo && SUDO_CMD="sudo"
  ${SUDO_CMD} cat /proc/cmdline /etc/kernel/cmdline 2>/dev/null | encrypt_output > NP_ConfigMateriel_R6_cmdline.txt
  ${SUDO_CMD} cat /etc/{default,sysconfig}/{grub,grub.d/*} 2>/dev/null | encrypt_output > NP_ConfigMateriel_R6_grub_cfg.txt
  ${SUDO_CMD} cat /etc/grub.conf 2>/dev/null | encrypt_output > NP_ConfigMateriel_R6_grub_cfg_old.txt

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NP_ConfigMateriel_R6"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_FAIL

  if ! grep -m1 -q smap /proc/cpuinfo; then
    debug "SMAP is not supported by the CPU."
    f_a=0
  else
    debug "SMAP is supported by the CPU."
    f_a=1
  fi

  is_package_installed sudo && SUDO_CMD="sudo"
  if ${SUDO_CMD} grep -q "nosmap" /proc/cmdline /etc/kernel/cmdline 2>/dev/null; then
    debug "SMAP is disabled in GRUB line."
    f_b=0
  else
    debug "SMAP is not disabled in GRUB line."
    f_b=1
  fi

  (( ${f_a:-0} && ${f_b:-0} )) && STATUS=RESULT_CHECK_PASS

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*RESULT_CHECK_PASS
recommendation: |
  Nous recommandons l'activation de la fonctionnalité SMAP. Cette recommandation peut nécessiter un changement de matériel en cas d'utilisation d'un processeur ne la prenant pas en charge.
level: enhanced
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/administration/guide/recommandations-de-configuration-materielle-de-postes-clients-et-serveurs-x86/
