# @copyright Copyright (c) 2021 Nicolas GRELLETY
# @license https://opensource.org/licenses/GPL-3.0 GNU GPLv3
# @link https://gitlab.internal.lan/octo-project/octobaselines
# @link https://github.com/nillyr/octobaselines
# @since 0.1.0

id: NP_ConfigMateriel_R10
title: Virtualisation des entrées/sorties
description: |
  Initialement conçue pour des applications associées à la virtualisation matérielle, cette fonctionnalité peut être avantageusement utilisée par un système d'exploitation classique en bloquant les attaques issues de périphériques malveillants disposant d'accès mémoire direct (DMA). Ces accès sont une menace importante pour la sécurité physique des systèmes car les périphériques qui en disposent sont capables de lire et d'écrire directement en mémoire physique, sans possibilité de contrôle par le système d'exploitation.

  Il est recommandé d'activer l'IOMMU en ajoutant la directive "iommu=force" à la liste des paramètres du noyau lors du démarrage en plus de celles déjà présentes dans les fichiers de configuration du chargeur de démarrage.

collection_cmd: |
  is_package_installed sudo && SUDO_CMD="sudo"
  ${SUDO_CMD} cat /proc/cmdline /etc/kernel/cmdline 2>/dev/null | encrypt_output > NP_ConfigMateriel_R10_cmdline.txt
  ${SUDO_CMD} cat /etc/{default,sysconfig}/{grub,grub.d/*} 2>/dev/null | encrypt_output > NP_ConfigMateriel_R10_grub_cfg.txt
  ${SUDO_CMD} cat /etc/grub.conf 2>/dev/null | encrypt_output > NP_ConfigMateriel_R10_grub_cfg_old.txt
  ${SUDO_CMD} lsmod | encrypt_output > NP_ConfigMateriel_R10_lsmod.txt
  ${SUDO_CMD} dmesg | grep -e DMAR -e IOMMU -e remapping | encrypt_output > NP_ConfigMateriel_R10_dmesg.txt
  ${SUDO_CMD} grep -e DMAR -e IOMMU -e remapping /var/log/dmesg* 2>/dev/null | encrypt_output > NP_ConfigMateriel_R10_dmesg_rotated.txt
  ${SUDO_CMD} grep iommu /etc/modprobe.d/*.conf | encrypt_output > NP_ConfigMateriel_R10_modprobe.txt
  ${SUDO_CMD} find /sys/kernel/iommu_groups/ -type l | encrypt_output > NP_ConfigMateriel_R10_iommu_groups.txt

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NP_ConfigMateriel_R10"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_FAIL

  is_package_installed sudo && SUDO_CMD="sudo"
  if ${SUDO_CMD} grep -q "iommu=force" /proc/cmdline /etc/kernel/cmdline /etc/{default,sysconfig}/{grub,grub.d/*} /etc/grub.conf 2>/dev/null; then
    STATUS=RESULT_CHECK_PASS
  fi

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*RESULT_CHECK_PASS
recommendation: |
  Dans la mesure du possible, nous recommandons d'activer cette fonctionnalité en ajoutant la directive "iommu=force".
  L'activation de cette fonctionnalité pouvant engendrer des instabilités matérielles, il est fortement recommandé de s'assurer du bon fonctionnement avant de déployer une telle mesure en production.

level: enhanced
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/administration/guide/recommandations-de-configuration-materielle-de-postes-clients-et-serveurs-x86/
