# @copyright Copyright (c) 2021 Nicolas GRELLETY
# @license https://opensource.org/licenses/GPL-3.0 GNU GPLv3
# @link https://gitlab.internal.lan/octo-project/octobaselines
# @link https://github.com/nillyr/octobaselines
# @since 1.0.0b

id: NP_ConfigMateriel_R7
title: Support de la famille d'instructions AES-NI
description: |
  Outre le gain significatif en performances qu'offrent ces instructions par rapport à des implémentations logicielles, en particulier pour le chiffrement de disques ou de protocoles réseau tels que TLS ou IPsec, l'avantage qu'apportent les instructions AES-NI réside dans la protection contre les attaques par canaux auxiliaires temporels basées sur les latences de cache. Dans certaines conditions favorables, ces attaques peuvent permettre à un processus utilisateur quelconque de récupérer la clé secrète de chiffrement d'un autre processus en quelques secondes par mesure des temps d'accès aux données en cache du CPU partagé entre les deux processus.

  Il est recommandé d'utiliser un processeur capable de supporter le jeu d'instruction AES-NI.

collection_cmd: |
  grep aes /proc/cpuinfo | encrypt_output > NP_ConfigMateriel_R7_cpu.txt

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NP_ConfigMateriel_R7"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_FAIL

  if grep -m1 -q aes /proc/cpuinfo; then
    debug "SMAP is not supported by the CPU."
    STATUS=RESULT_CHECK_PASS
  fi

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*RESULT_CHECK_PASS
recommendation: |
  Nous recommandons l'utilisation de processeurs supportant le jeu d'instructions AES-NI. Cette recommandation nécessite un changement de matériel.
level: enhanced
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/administration/guide/recommandations-de-configuration-materielle-de-postes-clients-et-serveurs-x86/
  - http://www.daemonology.net/papers/htt.pdf
