id: NT_OpenSSH_R4
title: Transfert et téléchargement de fichiers
description: |
  Le transfert de fichier, à la fois dans le sens montant (client vers serveur) et descendant (serveur vers client) est le deuxième cas d'usage relativement fréquent de SSH.

  SCP ou SFTP doivent être utilisés en lieu et place de protocoles historiques (RCP, FTP) pour du transfert ou du téléchargement de fichiers.

collection_cmd: |
  if [ -z "${DISTRIBUTION}" ]; then
        identify_distribution
  fi

  case ${DISTRIBUTION} in
      debian|ubuntu)
          dpkg -l > NT_OpenSSH_R4_packages_dpkg.txt
          ;;
      fedora|rhel|centos|rocky)
          if is_package_installed dnf; then
              dnf list installed > NT_OpenSSH_R4_packages_dnf.txt
          elif is_package_installed yum; then
              yum list installed > NT_OpenSSH_R4_packages_yum.txt
          else
              rpm -qa > NT_OpenSSH_R4_packages_rpm.txt
          fi
          ;;
      sles)
          if is_package_installed zypper; then
              zypper search --installed-only > NT_OpenSSH_R4_packages_zypper.txt
          else
              rpm -qa > NT_OpenSSH_R4_packages_rpm.txt
          fi
          ;;
      *)
          : > NT_OpenSSH_R3_packages_unsupported.txt
          ;;
  esac

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NT_OpenSSH_R4"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_PASS # (default: not installed)

  # https://pkgs.org/search/?q=ftp
  packages=(atftpd compat-golang-github-goftp-server-devel ftpd ftpd-ssl golang-goftp-server-devel golang-github-pin-tftp-dev perl-ftpd proftpd pure-ftpd pure-ftpd-common tftp-server tftpd tftpd-hpa twoftpd twoftpd-run vsftpd)
  for package in "${packages[@]}"; do
    is_package_installed "${package}" && STATUS=RESULT_CHECK_FAIL
  done

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*RESULT_CHECK_PASS
recommendation: |
  Nous recommandons de désinstailler les serveurs de transferts de fichiers différents de SSH.

  Pour cela, le _playbook_ Ansible suivant peut être utilisé :
  [source%linenums,yaml]
  [options="nowrap"]
  ----
  - name: Remove unsecure remote server packages
    hosts: all
    become: true

    ansible.builtin.apt:
      name:
        - atftpd
        - compat-golang-github-goftp-server-devel
        - ftpd
        - ftpd-ssl
        - golang-goftp-server-devel
        - golang-github-pin-tftp-dev
        - perl-ftpd
        - proftpd
        - pure-ftpd
        - pure-ftpd-common
        - tftp-server
        - tftpd
        - tftpd-hpa
        - twoftpd
        - twoftpd-run
        - vsftpd
      state: absent
    when: ansible_facts["os_family"] == "Debian"

    # change '.dnf' with '.yum' if needed
    ansible.builtin.dnf:
      name:
        - atftpd
        - compat-golang-github-goftp-server-devel
        - ftpd
        - ftpd-ssl
        - golang-goftp-server-devel
        - golang-github-pin-tftp-dev
        - perl-ftpd
        - proftpd
        - pure-ftpd
        - pure-ftpd-common
        - tftp-server
        - tftpd
        - tftpd-hpa
        - twoftpd
        - twoftpd-run
        - vsftpd
      state: absent
    when: ansible_facts["os_family"] == "RedHat"

    # require: ansible-galaxy collection install community.general
    community.general.zypper:
      name:
        - atftpd
        - compat-golang-github-goftp-server-devel
        - ftpd
        - ftpd-ssl
        - golang-goftp-server-devel
        - golang-github-pin-tftp-dev
        - perl-ftpd
        - proftpd
        - pure-ftpd
        - pure-ftpd-common
        - tftp-server
        - tftpd
        - tftpd-hpa
        - twoftpd
        - twoftpd-run
        - vsftpd
      state: absent
    when: ansible_facts["os_family"] == "Suse"
  ----

  Voir aussi :

  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
  - https://docs.ansible.com/ansible/latest/collections/community/general/zypper_module.html
level: minimal
severity: high
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/guide/recommandations-pour-un-usage-securise-dopenssh/
