id: NT_OpenSSH_R1
title: Version du protocole SSH
description: |
  Le protocole SSH existe en 2 versions : SSHv1 et SSHv2. SSHv1 présente des vulnérabilités structurelles qui ont été corrigées dans la version suivante. La version 1 du protocole est maintenant obsolète.

  Il est recommandé que seule la version SSHv2 soit utilisée.

  [NOTE]
  Depuis la version "7.4" du paquet "openssh-server", seule la version SSHv2 est disponible.

collection_cmd: |
  if is_package_installed openssh-server; then
    is_package_installed sudo && SUDO_CMD="sudo"
    IFS=" " read -r -a config_files <<< "$(get_all_sshd_config_files)"
    for file in "${config_files[@]}"; do
      printf "File: %s\n%s\n\n" "$(${SUDO_CMD} ls -lZ "${file}")" "$(${SUDO_CMD} cat "${file}" 2>/dev/null)" >> NT_OpenSSH_R1_config_files.txt
      printf "File: %s\n%s\n\n" "$(${SUDO_CMD} ls -lZ "${file}")" "$(${SUDO_CMD} sshd -T -f "${file}" 2>/dev/null)" >> NT_OpenSSH_R1_running_configs.txt
    done
  else
    : > NT_OpenSSH_R1.txt
  fi

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NT_OpenSSH_R1"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_PASS # (default = 2)

  if is_package_installed openssh-server; then
    is_package_installed sudo && SUDO_CMD="sudo"
    IFS=" " read -r -a config_files <<< "$(get_all_sshd_config_files)"
    for file in "${config_files[@]}"; do
      if ${SUDO_CMD} sshd -T -f "${file}" 2>/dev/null | grep -q -E '^protocol\s+(1\s*,\s*2|2\s*,\s*1|1)$'; then
        debug "'${file}' allows the use of SSHv1."
        STATUS=RESULT_CHECK_FAIL
      fi
    done
  else
    STATUS=RESULT_CHECK_NA
  fi

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*(RESULT_CHECK_PASS|RESULT_CHECK_NA)
recommendation: |
  Nous recommandons de modifier la configuration du service afin d'autoriser uniquement la version SSHv2.

  Pour cela, le _playbook_ Ansible suivant peut être utilisé :
  [source%linenums,yaml]
  [options="nowrap"]
  ----
  - name: Use SSHv2 only
    hosts: all
    become: true

    ansible.builtin.lineinfile:
      path: "{{ item }}"
      regexp: "^\s*Protocol"
      line: "Protocol 2"
    with_items:
      - /etc/ssh/sshd_config
  ----

  Voir aussi :

  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html

level: minimal
severity: high
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/guide/recommandations-pour-un-usage-securise-dopenssh/
