id: NT_OpenSSH_R28
title: X11Forwarding
description: |
  Dans ses fondements, une redirection X11 ressemble de très près à une redirection de flux distante. C'est une fonctionnalité qui doit donc être désactivée autant que possible. De façon générale, il est fortement déconseillé d'installer un serveur X sur un hôte ne nécessitant pas d'affichage graphique, de par les nombreuses failles de sécurité du X Window System.

  Quand une redirection X11 est active (exécution distante d'un client X11), la compromission de l'hôte distant peut conduire à une fuite d’information non maitrisée :

  - capture de frappes clavier de l’utilisateur ;
  - envoi de signaux non légitimes à des applications 3 ;
  - redirection d’affichage...

  Dans le cas où une redirection X11 est nécessaire, les clients X11 distants doivent être traités avec méfiance et disposer du moins de privilèges possibles.

collection_cmd: |
  if is_package_installed openssh-server; then
    is_package_installed sudo && SUDO_CMD="sudo"
    IFS=" " read -r -a config_files <<< "$(get_all_sshd_config_files)"
    for file in "${config_files[@]}"; do
      printf "File: %s\n%s\n\n" "$(${SUDO_CMD} ls -lZ "${file}")" "$(${SUDO_CMD} cat "${file}" 2>/dev/null)" >> NT_OpenSSH_R28_config_files.txt
      printf "File: %s\n%s\n\n" "$(${SUDO_CMD} ls -lZ "${file}")" "$(${SUDO_CMD} sshd -T -f "${file}" 2>/dev/null)" >> NT_OpenSSH_R28_running_configs.txt
    done
  else
    : > NT_OpenSSH_R28.txt
  fi

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NT_OpenSSH_R28"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_PASS

  if is_package_installed openssh-server; then
    is_package_installed sudo && SUDO_CMD="sudo"
    IFS=" " read -r -a config_files <<< "$(get_all_sshd_config_files)"
    for file in "${config_files[@]}"; do
      if { ! ${SUDO_CMD} sshd -T -f "${file}" | grep -E "^\s*x11forwarding\s+no$" ; } &>/dev/null; then
        STATUS=RESULT_CHECK_FAIL
      fi
    done

  else
    STATUS=RESULT_CHECK_NA
  fi

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*(RESULT_CHECK_PASS|RESULT_CHECK_NA)
recommendation: |
  Lorsque non nécessaire, nous recommandons de désactiver la redirection X11.

  Pour cela, le _playbook_ Ansible suivant peut être utilisé :
  [source%linenums,yaml]
  [options="nowrap"]
  ----
  - name: Block X11 Forwarding
    hosts: all
    become: true

    ansible.builtin.lineinfile:
      path: "{{ item }}"
      regexp: "^\s*X11Forwarding"
      line: "X11Forwarding no"
    with_items:
      - /etc/ssh/sshd_config
    notify:
      - Restart SSH service

    handlers:
      - name Restart SSH service
        become: true
        ansible.builtin.service:
          name: ssh
          state: restarted
  ----

  Voir aussi :

  - https://www.man7.org/linux/man-pages/man5/sshd_config.5.html
  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html

level: minimal
severity: high
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/guide/recommandations-pour-un-usage-securise-dopenssh/
