id: NT_OpenSSH_R17
title: Authentification d'un utilisateur
description: |
  Plusieurs mécanismes peuvent être utilisés pour permettre l'authentification d’un utilisateur. L'authentification d'un utilisateur doit se faire à l'aide d'un des mécanismes suivants, par ordre de préférence :

  - par cryptographie asymétrique ECDSA ;
  - par cryptographie asymétrique RSA ;
  - par cryptographie symétrique (tickets Kerberos par la GSSAPI) ;
  - PAM (ou BSD Auth) permettant de faire appel à des modules d'authentification tiers n'exposant pas le mot de passe utilisateur ou son condensat (OTP) ;
  - par mot de passe vis à vis d'une base de données comme passwd/shadow ou annuaire.

  Dans tous les cas, l'authentification d'un utilisateur avec un mot de passe vide ne doit pas être autorisé. De plus, l'opération d'authentification doit être d'une durée relativement courte et le nombre de tentatives doit être limité à une par connexion.

collection_cmd: |
  if is_package_installed openssh-server; then
    is_package_installed sudo && SUDO_CMD="sudo"
    IFS=" " read -r -a config_files <<< "$(get_all_sshd_config_files)"
    for file in "${config_files[@]}"; do
      printf "File: %s\n%s\n\n" "$(${SUDO_CMD} ls -lZ "${file}")" "$(${SUDO_CMD} cat "${file}" 2>/dev/null)" >> NT_OpenSSH_R17_config_files.txt
      printf "File: %s\n%s\n\n" "$(${SUDO_CMD} ls -lZ "${file}")" "$(${SUDO_CMD} sshd -T -f "${file}" 2>/dev/null)" >> NT_OpenSSH_R17_running_configs.txt
    done
  else
    : > NT_OpenSSH_R17.txt
  fi

check: |
  ################################################################################
  LANG=en_US.utf8

  RULE_ID="NT_OpenSSH_R17"
  HOSTNAME="$(hostname -f)"
  DATE="$(date +"%Y/%m/%d")"

  STATUS=RESULT_CHECK_PASS

  if is_package_installed openssh-server; then
    is_package_installed sudo && SUDO_CMD="sudo"
    IFS=" " read -r -a config_files <<< "$(get_all_sshd_config_files)"
    for file in "${config_files[@]}"; do
      if { ${SUDO_CMD} sshd -T -f "${file}" | grep -E "^\s*permitemptypasswords\s+yes" ; } &>/dev/null; then
        STATUS=RESULT_CHECK_FAIL
      fi
      if { ${SUDO_CMD} sshd -T -f "${file}" | grep -E "^\s*maxauthtries\s+([3-9]|[0-9]{2,})$" ; } &>/dev/null; then
        STATUS=RESULT_CHECK_FAIL
      fi
      if { ${SUDO_CMD} sshd -T -f "${file}" | grep -E "^\s*logingracetime\s+(3[1-9]+$|[3-9]\d{2,}$|[4-9]\d$)" ; } &>/dev/null; then
        STATUS=RESULT_CHECK_FAIL
      fi
    done

  else
    STATUS=RESULT_CHECK_NA
  fi

  printf "RULE_ID: %s\nHOSTNAME: %s\nDATE: %s\n\n%s\n" "${RULE_ID}" "${HOSTNAME}" "${DATE}" "${STATUS}" | encrypt_output
verification_type: CHECK_REGEX
expected: ^\s*(RESULT_CHECK_PASS|RESULT_CHECK_NA)
recommendation: |
  Nous recommandons de modifier la configuration du service SSH afin de bloquer l'authentification des utilisateurs ayant un mot de passe vide. Enfin, nous recommandons de limiter la durée de l'opération d'authentification.

  Pour cela, le _playbook_ Ansible suivant peut être utilisé :
  [source%linenums,yaml]
  [options="nowrap"]
  ----
  - name: Disable SSH Access via Empty Passwords
    hosts: all
    become: true

    ansible.builtin.lineinfile:
      path: "{{ item }}"
      regexp: "^\s*PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
    with_items:
      - /etc/ssh/sshd_config
    notify:
      - Restart SSH service

    ansible.builtin.lineinfile:
      path: "{{ item }}"
      regexp: "^\s*MaxAuthTries"
      line: "MaxAuthTries 2"
    with_items:
      - /etc/ssh/sshd_config
    notify:
      - Restart SSH service

    ansible.builtin.lineinfile:
      path: "{{ item }}"
      regexp: "^\s*LoginGraceTime"
      line: "LoginGraceTime 30"
    with_items:
      - /etc/ssh/sshd_config
    notify:
      - Restart SSH service

    handlers:
      - name Restart SSH service
        become: true
        ansible.builtin.service:
          name: ssh
          state: restarted
  ----

  Voir aussi :

  - https://www.man7.org/linux/man-pages/man5/sshd_config.5.html
  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html

level: minimal
severity: high
references:
  - https://www.ssi.gouv.fr/guide/recommandations-de-securite-relatives-a-un-systeme-gnulinux/
  - https://www.ssi.gouv.fr/guide/recommandations-pour-un-usage-securise-dopenssh/
